### ISSUE TITLE
RegisterDevice fails

### ISSUE THREAD

**Issue by ahartman** [4np/Example-APNS-Client-and-Server#2]
The ResisterDevice function fails with message:
Server error: dispatch(HTTP.ParserError.invalidStartLine).
Inserting a print statement at the error point proces attached output, looks like undecoded JSON garbage?
[vapor-registerDevice.txt](https://github.com/4np/Example-APNS-Client-and-Server/files/1887312/vapor-registerDevice.txt)

What is necessary to make this work? I was looking for an APNS-sending server and this works fine after having inserted my device manually in the database.
However, I also need to post data to the server and the RegisterDevice function is my example for that.

One other issue: when using localhost:8080/devices, I am seeing "WARNING: Response had no 'Content-Type' header" in the server output.

I am running Vapor 3 on Max OSX 10.13.4.

I hope you can help out.
Thanks n advance.
Regards, André Hartman, Belgium

**Comment by 4np** [comment]
This example was written for [Vapor **1**](https://github.com/4np/Example-APNS-Client-and-Server/blob/master/server/Package.swift). As Vapor **3** (which is currently still in beta) has a _lot_ of architectural changes (using `Codable`, non-blocking asynchronous architecture, `Swift-NIO`, configuration, apps vs droplets, etcetera) you probably need to rewrite / re-implement. But you can use this codebase for an example.

ps. Your textfile contains `Data`. Probably `String(bytes: data...)` will help?

**Comment by ahartman** [comment]
no longer using vapour
